### DISCUSSION TITLE
Persistent volumes for map data for many valhalla containers?

### DISCUSSION THREAD

**Discussion by Unrepentant-Atheist** [valhalla/valhalla#3405] [Q&A]
I'm playing with following idea: 5-10 instances of valhalla running. Each and every instance having access to the same docker-volume called "map-data", where the whole map of Europe is downloaded, cached, tiled, etc. etc.

Basically a persistent volume for:

```
#download some data and make tiles out of it
#NOTE: you can feed multiple extracts into pbfgraphbuilder
wget http://download.geofabrik.de/europe/switzerland-latest.osm.pbf http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf

#get the config and setup
mkdir -p valhalla_tiles
valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json

#build routing tiles
#TODO: run valhalla_build_admins?
valhalla_build_tiles -c valhalla.json switzerland-latest.osm.pbf liechtenstein-latest.osm.pbf

#tar it up for running the server
#either run this to build a tile index for faster graph loading times
valhalla_build_extract -c valhalla.json -v
```

Then when I start the `valhalla_service valhalla.json 1` it should access the persistent volume with said map data.

How would I go about that here?

**Comment by nilsnolde** [comment]
hm, it's possible. my question would first be: why would you like to do that? having many instances of valhalla memory mapping the same tar cannot be good. if it's about scale, valhalla_service happily handles more threads than 1. can you elaborate a little why you'd like to have multiple containers accessing the same data?

the solution is simply mapping a volume to the container (same host dir for every container then)

**Comment by Unrepentant-Atheist** [comment]
I tried with docker-compose.yml. It works, only problem is, the command keeps on executing in a loop after it finished once already.

```
---
version: "3.9"
services:
  snippet-box:
    image: valhalla/valhalla:run-latest
    container_name: valhalla
    restart: unless-stopped
    command:
      - /bin/bash
      - -c
      - |
        wget http://download.geofabrik.de/europe/switzerland-latest.osm.pbf http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf
        mkdir -p valhalla_tiles
        valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json
        valhalla_build_tiles -c valhalla.json switzerland-latest.osm.pbf liechtenstein-latest.osm.pbf
        valhalla_build_extract -c valhalla.json -v
    ports:
      - 8002:8002
    volumes:
      - map-data:/valhalla_tiles
volumes:
  map-data:
networks:
  default:
    name: valhallanet
    external: true
```
>  can you elaborate a little why you'd like to have multiple containers accessing the same data

Testing scalability. 10 users on 1 instance, 20 on another, 15 on yet another, etc. pp. but all have access to the same map data.
