### DISCUSSION TITLE
Extremly high network & i/o usage normal?

### DISCUSSION THREAD

**Discussion by Unrepentant-Atheist** [valhalla/valhalla#3406] [Q&A] [answered]
I run the valhalla service with this docker-compose.yml

```
---
version: "3.9"
services:
  snippet-box:
    image: valhalla/valhalla:run-latest
    container_name: valhalla
    restart: unless-stopped
    command:
      - /bin/bash
      - -c
      - |
        wget http://download.geofabrik.de/europe/switzerland-latest.osm.pbf http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf
        mkdir -p valhalla_tiles
        valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json
        valhalla_build_tiles -c valhalla.json switzerland-latest.osm.pbf liechtenstein-latest.osm.pbf
        valhalla_build_extract -c valhalla.json -v
        valhalla_service valhalla.json 1
    ports:
      - 8002:8002
    volumes:
      - map-data:/valhalla_tiles
volumes:
  map-data:
networks:
  default:
    name: valhallanet
    external: true
```

![image](https://user-images.githubusercontent.com/3938423/141802315-055fadd0-8cbe-4538-869f-b6709649c4f1.png)

Is this usage normal???
