### DISCUSSION TITLE
Can't access valhalla service outside of docker-VM on windows machines

### DISCUSSION THREAD

**Discussion by Unrepentant-Atheist** [valhalla/valhalla#3408] [Q&A]
I run the valhalla service with a docker-compose.yml like this:

```yml
    ---
    version: "3.9"
    services:
      snippet-box:
        image: valhalla/valhalla:run-latest
        container_name: valhalla
        restart: unless-stopped
        command:
          - /bin/bash
          - -c
          - |
            wget http://download.geofabrik.de/europe/switzerland-latest.osm.pbf http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf
            mkdir -p valhalla_tiles
            valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json
            valhalla_build_tiles -c valhalla.json switzerland-latest.osm.pbf liechtenstein-latest.osm.pbf
            valhalla_build_extract -c valhalla.json -v
        ports:
          - 8002:8002
        volumes:
          - map-data:/valhalla_tiles
    volumes:
      map-data:
    networks:
      default:
        name: valhallanet
        external: true
```
It works perfectly fine. Whenever I access the `http://IP-OF-VM:8002/route` with any browser, I get the `{"error_code":110,"error":"Insufficiently specified required parameter 'locations'","status_code":400,"status":"Bad Request"}` . So far so good.

When I ssh into the docker-VM and run 

`curl http://IP-OF-VM:8002/route --data '{"locations":[{"lat":47.365109,"lon":8.546824,"type":"break","city":"Zürich","state":"Altstadt"},{"lat":47.108878,"lon":8.394801,"type":"break","city":"6037 Root","state":"Untere Waldstrasse"}],"costing":"auto","directions_options":{"units":"kilometres"}}'` I get the correct output.

When I try my windows PC, open cmd or powershell and do the same command as above, I get `{"error_code":100,"error":"Failed to parse json request","status_code":400,"status":"Bad Request"}`.

What do?
