### DISCUSSION TITLE
How to run valhalla with docker compose correctly?

### DISCUSSION THREAD

**Discussion by Unrepentant-Atheist** [valhalla/valhalla#3410] [Q&A] [answered]
So I managed to get my valhalla instance running with docker compose with this 

```
---
version: "3.9"
services:
  snippet-box:
    image: valhalla/valhalla:run-latest
    container_name: valhalla
    restart: unless-stopped
    command:
      - /bin/bash
      - -c
      - |
        wget http://download.geofabrik.de/europe/switzerland-latest.osm.pbf http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf
        mkdir -p valhalla_tiles
        valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json
        valhalla_build_tiles -c valhalla.json switzerland-latest.osm.pbf liechtenstein-latest.osm.pbf
        valhalla_build_extract -c valhalla.json -v
        valhalla_service valhalla.json 1
    ports:
      - 8002:8002
    volumes:
      - map-data:/valhalla_tiles
volumes:
  map-data:
networks:
  default:
    name: valhallanet
    external: true
```
However, I noticed: What if the container shuts down and needs to be restarted? Then the whole process of downloading and rebuilding the tiles happens again, even though the tiles are already in the volume: map-data. How can I tweak this docker-compose.yml to reflect that?

I have no problem running 2 different docker-compose.yml, one for building the tiles like that, the other to just start the service again with access to map-data.

How do?

I'm thinking I have to put the ` > valhalla.json` inside valhalla_tiles and do

```
    command:
      - /bin/bash
      - -c
      - |
         valhalla_build_extract -c /valhalla_tiles/valhalla.json -v
         valhalla_service /valhalla_tiles/valhalla.json 1
``` 
or something like that in a different docker-compose.yml. I dunno.

**Comment by nilsnolde** [comment, marked as answer]
tons of strategies. for starters, you could check if valhalla_tiles.tar exists, if so, skip building. or compare timestamps or or or.. you could also just use our image: https://github.com/gis-ops/docker-valhalla. it supports most use cases quite well. the documentation is comprehensive.

fwiw, IMO no need to open 4 different tickets, basically asking all about docker setups. bit too spaghetti for a public forum

**Reply by Unrepentant-Atheist** [reply]
That solved it, easiest way is

```
---
version: '3.3'
services:
    valhalla:
        container_name: valhalla
        image: 'gisops/valhalla:latest'
        volumes:
            - custom_files:/custom_files
        ports:
            - 8002:8002
        environment:
          - tile_urls=http://download.geofabrik.de/europe/switzerland-latest.osm.pbf http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf
          - server_threads=2  # determines how many threads will be used to run the valhalla server
          - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
          - build_elevation=False  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
          - build_admins=False  # build admins db with "True" or "Force"
          - build_time_zones=False  # build timezone db with "True" or "Force"
          - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
          - force_rebuild=False  # forces a rebuild of the routing tiles with "True"
volumes:
  custom_files:
networks:
  default:
    name: valhallanet
    external: true
```

with env variables! Much obliged!
