### ISSUE TITLE
String field 'valhalla.TaggedValue.value' contains invalid UTF-8 data when parsing a protocol buffer.

### ISSUE THREAD

**Issue by CvRXX** [valhalla/valhalla#3465]
I'm trying to use the optimized_route with the use of the docker image.

However, I get an error when trying to use it:
```String field 'valhalla.TaggedValue.value' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. ```

The post returns with the following message:
```{"error_code":299,"error":"Unknown:Failed to parse intermediate request format:Failed parsing pbf in Odin::Worker","status_code":400,"status":"Bad Request"}```

I'm posting to http://localhost:8002/optimized_route with:
```{"locations":[{"lat":52.1,"lon":5.1,"name":"Carlos"},{"lat":52.0,"lon":5.0,"name":"Cato"}],"costing":"auto","directions_options":{"units":"kilometers"}}```

I'm using this docker-compose:
```
version: '3.0'
services:
  valhalla:
    image: gisops/valhalla:latest
    container_name: valhalla_latest
    ports:
      - 8002:8002
    #build:
    #  context: .
    #  args:
    #    - VALHALLA_UID=1000
    #    - VALHALLA_GID=1000
    volumes:
      - ./custom_files/:/custom_files
    environment:
      # Auto-download PBFs from Geofabrik
      - tile_urls=https://download.geofabrik.de/europe/netherlands-latest.osm.pbf
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      - use_tiles_ignore_pbf=False  # load existing valhalla_tiles.tar directly
      - build_elevation=False  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False  # build admins db with "True" or "Force"
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"
      # - path_extension=graphs  # this path will be internally appended to /custom_files; no leading or trailing path separator!
    # adapt to the expected build time
    # healthcheck: 
    #   test: curl --fail -s http://localhost:8002/status || exit 1
    #   interval: 1s
    #   retries: 10
    #   start_period: 2s
    #   timeout: 1s
```
This is the log of my output:
https://gist.github.com/CvRXX/76c6f7e13c28fbbd09f539315f655117

The current files in costume tiles are:
```
drwxrwxr-x 1 root   root    206 Dec 18 19:01 .
drwxr-xr-x 1 carlos carlos  128 Dec 18 18:45 ..
-rw-rw-r-- 1 root   root    272 Dec 18 18:53 duplicateways.txt
-rw-rw-r-- 1 root   root     65 Dec 18 19:01 file_hashes.txt
-rw-rw-r-- 1 root   root   1.1G Dec 18 18:46 netherlands-latest.osm.pbf
-rw-rw-r-- 1 root   root   6.8K Dec 18 18:46 valhalla.json
drwxrwxr-x 1 root   root      6 Dec 18 19:01 valhalla_tiles
-rw-rw-r-- 1 root   root   627M Dec 18 19:01 valhalla_tiles.tar
```
