### ISSUE TITLE
Bicycle directions take busy street instead of parallel bicycle lane

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#394]
(2016-05-12T07:03:05Z) @nvkelso : originally created valhalla/odin#324

I moved neighbourhoods and have been exploring new routes into the office. I noticed that Valhalla is sensitive to my starting location to determine if I should take a busy street on my 2nd leg or a parallel bike lane street for that 2nd leg.

**Defaults to Mission Street**, a busy & dangerous road:
- http://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=37.7104%2C-122.4349%3B37.7913%2C-122.3923#map=13/37.7515/-122.4150
- <img width="1135" alt="screen shot 2016-05-11 at 23 41 10" src="https://cloud.githubusercontent.com/assets/853051/15206338/3bc881e8-17d3-11e6-992d-8e2c470ec22b.png">

Moving it over to Geneva a block forces it to **take Alemany with the bike lane**, and then Mission which might be unavoidable / debatable versus going over to Glen Park and then along San Jose thru the low elevation cut?
- http://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=37.7120%2C-122.4333%3B37.7913%2C-122.3923#map=13/37.7523/-122.4150
- <img width="984" alt="screen shot 2016-05-11 at 23 41 58" src="https://cloud.githubusercontent.com/assets/853051/15206334/3148a752-17d3-11e6-9a80-eda9574cac9c.png">

If I reverse the trip, it's suggesting London Street on the 2nd to last leg (instead of Mission, good, or Alemany, sad) which is surprising because of the hills there:
- http://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=37.7913%2C-122.3918%3B37.7107%2C-122.4344#map=13/37.7545/-122.4073
- <img width="953" alt="screen shot 2016-05-11 at 23 56 48" src="https://cloud.githubusercontent.com/assets/853051/15206456/2db15cd2-17d4-11e6-89cc-6775b11211dd.png">

But really I was expecting to see a ride down the Geneva hill **towards the bay** with the following route, which is similar to what Google offers:
- http://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=37.7065%2C-122.4146%3B37.7913%2C-122.3923#map=13/37.7495/-122.4004
- <img width="910" alt="screen shot 2016-05-11 at 23 44 03" src="https://cloud.githubusercontent.com/assets/853051/15206330/1f2d9528-17d3-11e6-8809-06c4bf6f7e65.png">

At least we're way better than the competition, which doesn't seem to be elevation aware!
- <img width="1037" alt="screen shot 2016-05-11 at 23 40 52" src="https://cloud.githubusercontent.com/assets/853051/15206322/0cd32d7a-17d3-11e6-8086-f611570e23e7.png">

/cc @dnesbitt61

**Comment by nvkelso** [comment]
Here's the filtering we ended up with for the [Bike Map v2](https://mapzen.com/blog/bike-map-v2/) (below).

![legend3](https://user-images.githubusercontent.com/853051/27707894-c9e53b22-5ccb-11e7-8075-191fec35c4df.png)

We're coloring things **green** for beginner and intermediate cyclists. **Orange** is for intermediate and **dashed orange** is for advanced cyclists. 

**Top level highlights:**

- `highway: [`_the usual ones... and:_ `residential, living_street, unclassified, bridleway, corridor]`
- `cycleway: [lane, opposite, opposite_lane, sidepath, track, opposite_track, buffered_lane, cycleway_greenway]`
- `bicycle: [no, dismount, use_sidepath]`
- `surface: [cobblestone, unpaved, grass, ground, dirt, earth, sand, woodchips, pebblestones, compacted]`
- `"ramp:bicycle": yes` _(this one is transformed from OSM via vector tile transform)_

Another big difference seems to be we show footpaths as bike okay unless proven not with `bicycle: no`.

**Full snippet:**

- https://github.com/tangrams/walkabout-style/blob/gh-pages/layers/bike-interlay.yaml#L663-L741

```
    # green
    bike_tier1_off_road_filter:
        any:
            - { is_bicycle_related: true, kind_detail: [cycleway, path, pedestrian, steps, bridleway, raceway, corridor] }
            - cycleway: [sidepath, track, opposite_track, buffered_lane]
            - cycleway_left: [sidepath, track, opposite_track, buffered_lane]
            - cycleway_right: [sidepath, track, opposite_track, buffered_lane]
    casing_bike_tier1_off_road_track_filter_left:
        cycleway_left: [sidepath, track, opposite_track, buffered_lane]
    casing_bike_tier1_off_road_track_filter_right:
        cycleway_right: [sidepath, track, opposite_track, buffered_lane]
    bike_tier1_off_road_steps_filter:
        { is_bicycle_related: true, kind_detail: [steps] }

    #green, but brown (I know, right)
    bike_tier1_off_road_footway_filter:
        { is_bicycle_related: true, kind_detail: [footway] }

    #blue ferry
    bike_tier1_ferry_filter:
        { kind: ferry, is_bicycle_related: true }

    # greenway
    greenway_on_road_filter:
        all:
            - is_bicycle_related: true
        any:
            - { kind_detail: [living_street, unclassified], bicycle_network: true }
            - { kind_detail: [living_street, unclassified], walking_network: true }   # some funk in Portland, OR
            - { kind_detail: [living_street, unclassified], cycleway: true }   # eg shared_lane – really the server should provide bicycle_network
            - { cycleway: cycleway_greenway }
    greenway_on_road_casing_filter:
        all:
            - is_bicycle_related: true
        any:
            - { kind_detail: [residential, living_street, unclassified], cycleway_left: true }   # lane casings
            - { kind_detail: [residential, living_street, unclassified], cycleway_right: true }  # lane casings

    # brown
    bike_tier1_off_road_track_filter:
        all:
            - { is_bicycle_related: true, kind_detail: [track, footway] }
    bike_tier1_off_road_unpaved_filter:
        any:
            - surface: [unpaved, grass, ground, dirt, earth, sand, woodchips, pebblestones, compacted]
            - kind_detail: [bridleway, corridor]

    # orange
    bike_tier2_on_road_protected_filter:
        all:
            - not:
                - kind_detail: [cycleway, track, path, pedestrian, living_street, unclassified, footway, steps, raceway, bridleway, corridor]
        any:
            - cycleway: [lane, opposite, opposite_lane]
            - cycleway_left: [lane, opposite, opposite_lane]
            - cycleway_right: [lane, opposite, opposite_lane]
    casing_bike_tier2_on_road_protected_filter_left:
        cycleway_left: [lane, opposite, opposite_lane]
    casing_bike_tier2_on_road_protected_filter_right:
        cycleway_right: [lane, opposite, opposite_lane]

    # orange is major road or highway
    # green if minor road
    bike_tier3_on_road_not_protected_filter:
        all:
            - is_bicycle_related: true
            - not:
                any:
                    - kind_detail: [cycleway, track, path, pedestrian, living_street, unclassified, footway, steps, raceway, bridleway, corridor]
                    - cycleway: [lane, opposite, opposite_lane, sidepath, track, opposite_track, buffered_lane, cycleway_greenway]
                    - cycleway_left: [lane, opposite, opposite_lane, sidepath, track, opposite_track, buffered_lane]
                    - cycleway_right: [lane, opposite, opposite_lane, sidepath, track, opposite_track, buffered_lane]
    casing_bike_tier3_on_road_not_protected_filter_left:
        cycleway_left: [shared_lane, shared_busway, share_busway]
    casing_bike_tier3_on_road_not_protected_filter_right:
        cycleway_right: [shared_lane, shared_busway, share_busway]

    # red: dismount bike (or no bike)
    no_bike_tier4_filter:
        any:
            # https://www.openstreetmap.org/way/280439276#map=18/46.56290/15.62873&layers=C
            - bicycle: [no, dismount, use_sidepath]
            - surface: cobblestone
```
