### ISSUE TITLE
UTF8 Related protobuf error

### ISSUE THREAD

**Issue by cazitouni** [valhalla/valhalla#4600]
Hello, 

I'm opening this issues because I got a bug related to a protobuff utf8 issue using the gis ops docker container with the following docker compose 

```
version: '3.0'
services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - ./custom_files/:/custom_files
    environment:
      # The tile_file must be located in the `custom_files` folder.
      # The tile_file has priority and is used when valid.
      # If the tile_file doesn't exist, the url is used instead.
      # Don't blank out tile_url when you use tile_file and vice versa.
      - tile_urls=https://download.geofabrik.de/europe/france/alsace-latest.osm.pbf
      # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
      - min_x=7.3369 # -> Albania | -180 -> World
      - min_y=48.1944 # -> Albania | -90  -> World
      - max_x=8.1059 # -> Albania |  180 -> World
      - max_y=48.9663 # -> Albania |  90  -> World
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - force_rebuild_elevation=False
```

Most of the times the routing works well but sometimes it returns the following error

```
valhalla-valhalla-1  | 33 2024/02/23 07:51:36.580799 POST /route HTTP/1.1
valhalla-valhalla-1  | 2024/02/23 07:51:36.581038 [INFO] Got Loki Request 33
valhalla-valhalla-1  | 2024/02/23 07:51:36.592816 [INFO] Got Thor Request 33
valhalla-valhalla-1  | 2024/02/23 07:51:36.597395 [INFO] algorithm::bidirectional_a*
valhalla-valhalla-1  | [libprotobuf ERROR google/protobuf/wire_format_lite.cc:618] String field 'valhalla.StreetName.value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
valhalla-valhalla-1  | 2024/02/23 07:51:36.600802 [INFO] Got Odin Request 33
valhalla-valhalla-1  | [libprotobuf ERROR google/protobuf/wire_format_lite.cc:618] String field contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
valhalla-valhalla-1  | 2024/02/23 07:51:36.606954 [ERROR] Failed parsing pbf in Odin::Worker
valhalla-valhalla-1  | 33 2024/02/23 07:51:36.607315 400 285
```

This is the case for example using this request 

`curl http://localhost:8002/route --data '{"locations":[{"lat":48.571908,"lon":7.762687},{"lat":48.572642,"lon":7.761721}],"costing":"auto","directions_options":{"units":"kilometers"}}' | jq '.'`

I don't know if i'm doing something wrong.
I've also tried with a different pbf provided by openstreetmap france but the result still the same.

Let me know if you have any idea about this bug or if you need any more infos. 
Kind regards, Clément.
