### ISSUE TITLE
sources_to_targets returns bad results for time and distance

### ISSUE THREAD

**Issue by urosjarc** [valhalla/valhalla#4979]
Reproducing problems...

# 1. Use this docker-compose.yaml
```
services:
    valhalla:
        image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
        ports:
            - "8002:8002"
        volumes:
            - ./custom_files/:/custom_files
        environment:
            # The tile_file must be located in the `custom_files` folder.
            # The tile_file has priority and is used when valid.
            # If the tile_file doesn't exist, the url is used instead.
            # Don't blank out tile_url when you use tile_file and vice versa.
            - tile_urls=https://download.geofabrik.de/europe/slovenia-latest.osm.pbf
            # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
            - min_x=13.3715
            - min_y=45.4162
            - max_x=16.6111
            - max_y=46.8793
            - use_tiles_ignore_pbf=True
            - force_rebuild=False
            - force_rebuild_elevation=False
            - build_elevation=True
            - build_admins=True
            - build_time_zones=True
            - server_threads=16
```
2. Run docker container

`sudo docker compose up valhalla`

3. Execute this request on `sources_to_targets`

[valhalla_request.json](https://github.com/user-attachments/files/17822227/valhalla_request.json)

4. You should get following response...

[valhalla_response.json](https://github.com/user-attachments/files/17822228/valhalla_response.json)

5. In the response check

Start index: 983
End index: 587

Matrix response is 2019m and 192 seconds.
But in reality its 78m and 7 seconds

![image](https://github.com/user-attachments/assets/16d3693e-4fe3-4f3c-9a57-e16eb7bc3b4e)
